spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security1
    username: root
    password: 8112840zhang
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.web_split.entity